name = "workers-kv-from-rust"
main = "build/index.js"
compatibility_date = "2026-07-01"
workers_dev = true

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[observability]
enabled = true

[[kv_namespaces]]
binding = "COMMON"
id = "00000000000000000000000000000000"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/wrangler/configuration
