account_id = ""
kv-namespaces = [
  {binding = "KV", id = "", preview_id = ""},
]
name = "simple-feedback-worker"
route = ""
type = "rust"
workers_dev = true
zone_id = ""

# Fill-out account_id, kv-namespace id and preview_id, zone_id. These are available in your cloudflare dashboard.
