compatibility_date = "2021-10-10"
compatibility_flags = ["formdata_parser_supports_files"] # required
name = "workers-kv-from-rust"
type = "javascript"
workers_dev = true
kv_namespaces = [
  {binding = "COMMON", id = "00000000000000000000000000000000", preview_id = "00000000000000000000000000000000"},
]

[vars]
WORKERS_RS_VERSION = "0.0.6"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
